# Generated by Django 3.1.2 on 2020-11-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publishers',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
